env:
  global:
  - CODECLIMATE_REPO_TOKEN=d8c5ae082832ed947bc6e673ebfbd1592278fa04633401bf7d180687238fa397
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct;
    else git log -1 --skip 1 --pretty=format:%ct; fi)
language: python
matrix:
  include:
    - python: '2.7'
      env: KERAS_BACKEND=tensorflow
    - python: '3.5'
      env: KERAS_BACKEND=tensorflow
    - python: '3.6'
      env: KERAS_BACKEND=tensorflow
    - python: '2.7'
      env: KERAS_BACKEND=theano
    - python: '3.5'
      env: KERAS_BACKEND=theano
    - python: '3.6'
      env: KERAS_BACKEND=theano
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]];
  then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION Cython numpy=1.13 scipy tensorflow keras
  scikit-learn;
- source activate test-environment
- pip install git+git://github.com/Theano/Theano.git; conda install mkl-service && export MKL_THREADING_LAYER=GNU;
- pip install coverage==4.3
- pip install pytest "pytest-cov<2.6"
- pip install argparse
- pip install codeclimate-test-reporter
- rm -f tslearn/*.c
- python setup.py build_ext --inplace
script:
# run keras backend init to initialize backend config
- python -c "import keras.backend";
  sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)";
- python -m pytest -v tslearn tslearn/tests/ --doctest-modules --ignore tslearn/docs $KERAS_IGNORE --cov=tslearn
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then codeclimate-test-reporter; fi
notifications:
  email: false

