language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install scipy
  - pip install numpy
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
script: nosetests --with-doctest